"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloProvider } from "@apollo/client";
import { client } from "@/services/apollo-client";
import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import AuthProvider from "@/context/auth";
import LoaderProvider, { useLoader } from "@/context/loader";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { loader } = useLoader();
  return (
    <html lang="en">
      <ApolloProvider client={client}>
        <LoaderProvider>
          <AuthProvider>
            <body className={`${inter.className} bg-slate-700 `}>
              <ToastContainer />
              <Navbar />
              {children}
            </body>
          </AuthProvider>
        </LoaderProvider>
      </ApolloProvider>
    </html>
  );
}
